language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
after_script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: "CUnSh+8WfGwb5eI8XLv6vuR7x1vtvjp/722dcXAo469MfVF1tgXvsuxWG6E5Vs8cJSZxYFZGgwbrCO4ks8vJzf7gNk4UgTzhEZo8skbZOV0Lb51Hf/AQp8hV0IsAtG/lN94NaGCRDUXxclkfPIXDzCu3wRiYpW7S1q11WHJvXJroxI6us/3iibjwNg6uqQI8zPUgVkMJ2JTq5hLJXAskJBQUc85uaZXp3YT6yjYmGCC76mpJ6GDZA1pLRJNpxcqcOdj31vsnVpmPD7IxlFWBzjPkqKcalNE2AbwjaVS+Gb4KlBIfqFUJHudXVYQdY91KRaPB+61g936hb2RHrdb2dJmu8p1NK9cn2xw/RnC3CC1WAo+1jvC0EK70cxeAfilOaQjTSuI4xZ/1nwVSfBNYFGZBbmwC4mCSmPMuR7+joQF54vhFblnvWCER0JBjkhWAvhh2dHdArjmKT8wwlivTqBA7rasEBE0ZTi3HT6QdBkzc6BUqMwKZv/5sOMP4sneaYbsBzMFK3EfUDxU6d0Xd+lAh/OnkO1Wn9vefXxFONIPuA+DZB1bsDwCpwtIZJf2oCwikjBkT9Hude3SWpV+/kkQbrf+3dw3JbNrwhyEXgoyK/LIkUnC0dq+ocTnaI3yB5ytcFWeEVAjgCiDGR4/quOVC6kUb+crjw36Nb3nJo0k="
  app: fista-pedalroom
